apiVersion: apps/v1
kind: Deployment
metadata: 
  name: zookeeper
spec:
  template:
    spec:
      containers:
      - image: confluentinc/cp-zookeeper:7.0.1
        name: zookeeper-container
        ports:
        - containerPort: 2181
        env:
        - name: ZOOKEEPER_CLIENT_PORT
          value: "2181"
        - name: ZOOKEEPER_TICK_TIME
          value: "2000"   
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"     